### ISSUE TITLE
Warning. Plagiarism!

### ISSUE THREAD

**Issue by DenQ** [yi-ge/js-tree-list#2]
@yi-ge Please tell me 
1. Why you copied all the source codes from my projects into your project so boldly? And laid out in the public domain as if you are the author.
2. What's new in your project that the original project does not provide?
3. Where is the reference to the original projects? And its author?

Link on original projects:
1. https://github.com/DenQ/iron-tree
2. https://github.com/DenQ/list-to-tree

**Comment by yi-ge** [comment]
@DenQ 这只是一个练习，并且只是整合两个项目，将语法转为ES6并添加了一些功能，没有及时添加您的相关信息，很抱歉。无意抄袭，抱歉。

2018年03月15日更新：根据您邮件回复，我已经注明相关信息。谢谢您！

**Comment by yi-ge** [comment]
@DenQ It's just an exercise. I'm sorry I didn't want to plagiarism, but I just wanted to improve the code.

**Comment by yi-ge** [comment]
@DenQ I am very sorry for my mistake.

**Comment by yi-ge** [comment]
@DenQ 
Transfer ownership
This repository is being transferred to @DenQ.
